name: SATURN 444 LK

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 43800

    steps:
    - name: Disable Firewall Profiles
      shell: cmd
      run: |
        netsh advfirewall set allprofiles state off
        if errorlevel 1 echo Failed to disable firewall. Continuing...

    - name: Install Necessary Packages
      shell: cmd
      run: |
        @echo off
        set maxRetries=3
        set retryCount=0

        :: Install chrome-remote-desktop-host
        :installChromeRemoteDesktop
        choco list --local-only chrome-remote-desktop-host | findstr /i "chrome-remote-desktop-host"
        if %errorlevel% equ 0 (
          echo chrome-remote-desktop-host is already installed. Skipping installation.
          goto installGoogleChrome
        )

        echo Installing chrome-remote-desktop-host...
        choco install chrome-remote-desktop-host -y --ignore-checksums
        if %errorlevel% neq 0 (
          set /a retryCount+=1
          if %retryCount% LSS %maxRetries% (
            echo Retrying chrome-remote-desktop-host install (%retryCount%/%maxRetries%)
            timeout /t 10 > nul
            goto installChromeRemoteDesktop
          ) else (
            echo chrome-remote-desktop-host failed to install after multiple attempts.
            exit /b 1
          )
        )

        set retryCount=0

        :: Install googlechrome
        :installGoogleChrome
        choco list --local-only googlechrome | findstr /i "googlechrome"
        if %errorlevel% equ 0 (
          echo googlechrome is already installed. Skipping installation.
          goto :eof
        )

        echo Installing googlechrome...
        choco install googlechrome -y --ignore-checksums
        if %errorlevel% neq 0 (
          set /a retryCount+=1
          if %retryCount% LSS %maxRetries% (
            echo Retrying googlechrome install (%retryCount%/%maxRetries%)
            timeout /t 10 > nul
            goto installGoogleChrome
          ) else (
            echo googlechrome failed to install after multiple attempts.
            exit /b 1
          )
        )

    - name: Set Desktop Wallpaper
      shell: cmd
      run: |
        @echo off
        set WallpaperUrl=https://i.ibb.co/7QBjY1q/20241214-020008.jpg
        set WallpaperPath=%USERPROFILE%\Documents\wallpaper.jpg

        curl -o "%WallpaperPath%" "%WallpaperUrl%"
        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "%WallpaperPath%" /f
        rundll32.exe user32.dll, UpdatePerUserSystemParameters

    - name: Download and Extract Free Fire Ripper
      shell: cmd
      run: |
        @echo off
        cd %USERPROFILE%\Documents
        curl -o ffripper.zip "https://drive.usercontent.google.com/download?id=11EUFz6hufNT1g56-CmOJw9_KxMERZxhe&export=download"
        7z x ffripper.zip -y

    - name: Start Chrome Remote Desktop
      shell: cmd
      run: |
        @echo off
        if exist "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" (
          "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        ) else if exist "%PROGRAMFILES%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" (
          "%PROGRAMFILES%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        ) else (
          echo Chrome Remote Desktop's remoting_start_host.exe not found.
          exit /b 1
        )

    - name: Create Symbolic Links
      shell: cmd
      run: |
        @echo off
        mklink "%USERPROFILE%\Desktop\Free Fire.lnk" "%USERPROFILE%\Documents\FenixGaga\Engine\ProjectTitan.exe"
        mklink "%USERPROFILE%\Desktop\Ninjaripper.lnk" "%USERPROFILE%\Documents\ninjaripper\x86\NinjaRipper.exe"
        mklink "%USERPROFILE%\Desktop\Noesis.lnk" "%USERPROFILE%\Documents\noesis\Noesis64.exe"

    - name: Start Remote Desktop Session
      shell: cmd
      run: |
        @echo off
        echo Connecting to VM with Remote Desktop
        echo %code% --pin=444444

    - name: Keep Connection Active
      shell: cmd
      run: |
        @echo off
        for /l %%i in (1,1,43800) do (
          echo Keeping connection active - Minute %%i
          timeout /t 60 > nul
        )
