name: SATURN 444 LK

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 43800

    steps:
    - name: Disable Firewall Profiles
      shell: cmd
      run: |
        netsh advfirewall set allprofiles state off

    - name: Install Necessary Packages
      shell: cmd
      run: |
        @echo off
        set maxRetries=3
        set /a retryCount=0
        :retry
        if %retryCount% GEQ %maxRetries% (
          echo Installation failed after multiple attempts.
          exit /b 1
        )
        choco install chrome-remote-desktop-host -y --ignore-checksums || (
          echo Retrying chrome-remote-desktop-host install...
          set /a retryCount+=1
          timeout /t 10
          goto retry
        )
        set retryCount=0
        :retry2
        if %retryCount% GEQ %maxRetries% (
          echo Installation failed after multiple attempts.
          exit /b 1
        )
        choco install googlechrome -y --ignore-checksums || (
          echo Retrying googlechrome install...
          set /a retryCount+=1
          timeout /t 10
          goto retry2
        )

    - name: Set Wallpaper
      shell: cmd
      run: |
        @echo off
        set WallpaperUrl=https://i.ibb.co/7QBjY1q/20241214-020008.jpg
        set WallpaperPath=%USERPROFILE%\Documents\wallpaper.jpg
        bitsadmin /transfer myDownloadJob %WallpaperUrl% %WallpaperPath%
        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "%WallpaperPath%" /f
        rundll32.exe user32.dll, UpdatePerUserSystemParameters

    - name: Download and Extract Free Fire Ripper
      shell: cmd
      continue-on-error: true
      run: |
        @echo off
        cd %USERPROFILE%\Documents
        bitsadmin /transfer myDownloadJob https://drive.usercontent.google.com/download?id=11EUFz6hufNT1g56-CmOJw9_KxMERZxhe&export=download ffripper.zip
        7z x ffripper.zip -y || (
          echo Download or extraction failed.
          exit /b 1
        )

    - name: Start Chrome Remote Desktop
      shell: cmd
      run: |
        @echo off
        echo Starting Chrome Remote Desktop...
        set "chromeRemoteDesktopPath=%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        set "authCode=%code%"
        set "pin=444444"
        set "redirectUrl=https://remotedesktop.google.com/_/oauthredirect"
        
        REM Check for existence of remoting_start_host.exe
        if exist "%chromeRemoteDesktopPath%" (
          "%chromeRemoteDesktopPath%" --code="%authCode%" --pin=%pin% --redirect-url=%redirectUrl%
        ) else (
          echo Chrome Remote Desktop's remoting_start_host.exe not found.
          exit /b 1
        )

    - name: Create Symbolic Links
      shell: cmd
      run: |
        @echo off
        mklink "%USERPROFILE%\Desktop\Free Fire.lnk" "%USERPROFILE%\Documents\FenixGaga\Engine\ProjectTitan.exe"
        mklink "%USERPROFILE%\Desktop\Ninjaripper.lnk" "%USERPROFILE%\Documents\ninjaripper\x86\NinjaRipper.exe"
        mklink "%USERPROFILE%\Desktop\Noesis.lnk" "%USERPROFILE%\Documents\noesis\Noesis64.exe"

    - name: Keep Connection Active
      shell: cmd
      run: |
        @echo off
        set /a i=43800
        :loop
        if %i% LEQ 0 exit /b 0
        echo %i%
        timeout /t 60
        set /a i-=1
        goto loop
