name: SATURN 444 LK

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 43800

    steps:
    - name: Disable Firewall Profiles
      shell: cmd
      run: |
        netsh advfirewall set allprofiles state off
        if errorlevel 1 echo Failed to disable firewall. Continuing...

    - name: Install Necessary Packages
      shell: cmd
      run: |
        @echo off
        set maxRetries=3
        set retryCount=0

        :installChromeRemoteDesktop
        choco install chrome-remote-desktop-host -y --ignore-checksums
        if errorlevel 1 (
          set /a retryCount+=1
          if %retryCount% LSS %maxRetries% (
            echo Retrying chrome-remote-desktop-host install (%retryCount%/%maxRetries%)
            timeout /t 10
            goto installChromeRemoteDesktop
          ) else (
            echo chrome-remote-desktop-host failed to install after multiple attempts.
            exit /b 1
          )
        )

        set retryCount=0
        :installGoogleChrome
        choco install googlechrome -y --ignore-checksums
        if errorlevel 1 (
          set /a retryCount+=1
          if %retryCount% LSS %maxRetries% (
            echo Retrying googlechrome install (%retryCount%/%maxRetries%)
            timeout /t 10
            goto installGoogleChrome
          ) else (
            echo googlechrome failed to install after multiple attempts.
            exit /b 1
          )
        )

    - name: Set Wallpaper
      shell: cmd
      run: |
        set WallpaperUrl=https://i.ibb.co/7QBjY1q/20241214-020008.jpg
        set WallpaperPath=%USERPROFILE%\Documents\wallpaper.jpg
        curl -o "%WallpaperPath%" "%WallpaperUrl%"
        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "%WallpaperPath%" /f
        rundll32.exe user32.dll,UpdatePerUserSystemParameters

    - name: Download and Extract Free Fire Ripper
      shell: cmd
      continue-on-error: true
      run: |
        cd "%USERPROFILE%\Documents"
        curl -o ffripper.zip "https://drive.usercontent.google.com/download?id=11EUFz6hufNT1g56-CmOJw9_KxMERZxhe&export=download"
        7z x ffripper.zip -y
        if errorlevel 1 (
          echo Download or extraction failed.
          exit /b 1
        )

    - name: Start Chrome Remote Desktop
      shell: cmd
      continue-on-error: true
      run: |
        @echo off
        set paths="%ProgramFiles(x86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" "%ProgramFiles%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        for %%p in (%paths%) do (
          if exist %%p (
            start "" %%p
            goto :eof
          )
        )
        echo Chrome Remote Desktop's remoting_start_host.exe not found.

    - name: Create Symbolic Links
      shell: cmd
      run: |
        mklink "%USERPROFILE%\Desktop\Free Fire.lnk" "%USERPROFILE%\Documents\FenixGaga\Engine\ProjectTitan.exe"
        mklink "%USERPROFILE%\Desktop\Ninjaripper.lnk" "%USERPROFILE%\Documents\ninjaripper\x86\NinjaRipper.exe"
        mklink "%USERPROFILE%\Desktop\Noesis.lnk" "%USERPROFILE%\Documents\noesis\Noesis64.exe"

    - name: Start Remote Desktop Session
      shell: cmd
      continue-on-error: true
      run: |
        echo Connecting to VM with Remote Desktop
        echo %{{ inputs.code }} --pin=444444

    - name: Keep Connection Active
      shell: cmd
      run: |
        @echo off
        set /a minutes=43800
        :keepAlive
        echo %minutes% minutes remaining
        timeout /t 60
        set /a minutes-=1
        if %minutes% GTR 0 goto keepAlive
